category: Exceptions
description: Ratel notifies Honeybadger about exceptions.
extra-source-files:
- CHANGELOG.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: tfausak/ratel
library:
  dependencies:
  - aeson ==0.11.*
  - base ==4.9.*
  - bytestring ==0.10.*
  - case-insensitive ==1.2.*
  - containers ==0.5.*
  - http-client ==0.4.*
  - http-client-tls ==0.2.*
  - http-types ==0.9.*
  - text ==1.2.*
  - uuid ==1.3.*
  other-modules:
  - Paths_ratel
  source-dirs: library
license: MIT
maintainer: Taylor Fausak
name: ratel
synopsis: Notify Honeybadger about exceptions.
tests:
  ratel-test-suite:
    dependencies:
    - base
    - ratel
    - tasty ==0.11.*
    - tasty-hspec ==1.1.*
    main: Main.hs
    source-dirs: test-suite
version: '0.1.3'
